"""
Export PyTorch/PredicateMLP weights to SWI-Prolog facts format.

This utility converts trained neural network weights into Prolog facts
that can be loaded by the sro_decoder_mlp.pl inference engine.

Usage:
    python export_weights_to_prolog.py --model checkpoint.pt --output weights.pl
    python export_weights_to_prolog.py --random --output weights.pl  # Random init
"""

import argparse
import sys
from pathlib import Path
from typing import List, Tuple

# Try to import torch, but allow running without it for format generation
try:
    import torch
    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False


def format_prolog_list(values: List[float], precision: int = 8) -> str:
    """Format a list of floats as a Prolog list."""
    formatted = [f"{v:.{precision}f}" for v in values]
    return "[" + ", ".join(formatted) + "]"


def export_layer_weights(
    layer_id: int,
    weights: List[List[float]],
    bias: List[float],
    activation: str,
    precision: int = 8
) -> str:
    """
    Export a single layer's weights to Prolog facts.

    Args:
        layer_id: Layer index (0-based)
        weights: Weight matrix as list of rows
        bias: Bias vector
        activation: Activation function name (linear, relu, swish, sigmoid, softmax)
        precision: Decimal precision for floats

    Returns:
        Prolog facts as string
    """
    lines = []
    lines.append(f"% Layer {layer_id}: {len(weights[0])} -> {len(weights)}, {activation}")

    # Weight rows
    for row_idx, row in enumerate(weights):
        prolog_row = format_prolog_list(row, precision)
        lines.append(f"weight({layer_id}, {row_idx}, {prolog_row}).")

    # Bias
    prolog_bias = format_prolog_list(bias, precision)
    lines.append(f"bias({layer_id}, {prolog_bias}).")

    # Activation
    lines.append(f"layer_activation({layer_id}, {activation}).")

    # Config
    in_features = len(weights[0])
    out_features = len(weights)
    lines.append(f"layer_config({layer_id}, {in_features}, {out_features}).")

    return "\n".join(lines)


def export_mlp_weights(
    layer_weights: List[Tuple[List[List[float]], List[float], str]],
    output_path: str,
    model_name: str = "SRO Decoder Ring MLP"
) -> None:
    """
    Export full MLP weights to a Prolog file.

    Args:
        layer_weights: List of (weights, bias, activation) tuples per layer
        output_path: Output file path
        model_name: Name for documentation
    """
    with open(output_path, 'w') as f:
        # Header
        f.write(f"% {model_name} - Weights\n")
        f.write("% Generated by export_weights_to_prolog.py\n")
        f.write("%\n")
        f.write("% Load with: ?- load_weights('weights.pl').\n")
        f.write("% Then:      ?- mlp([0.5], Energy).\n")
        f.write("%\n\n")

        # Discontiguous declarations (required for interleaved facts)
        f.write(":- discontiguous weight/3.\n")
        f.write(":- discontiguous bias/2.\n")
        f.write(":- discontiguous layer_activation/2.\n")
        f.write(":- discontiguous layer_config/3.\n\n")

        # Export each layer
        for layer_id, (weights, bias, activation) in enumerate(layer_weights):
            f.write(export_layer_weights(layer_id, weights, bias, activation))
            f.write("\n\n")

    print(f"Exported {len(layer_weights)} layers to {output_path}")


def generate_random_weights(
    architecture: List[Tuple[int, int, str]]
) -> List[Tuple[List[List[float]], List[float], str]]:
    """
    Generate random weights for a given architecture.

    Args:
        architecture: List of (in_features, out_features, activation) tuples

    Returns:
        List of (weights, bias, activation) tuples
    """
    import random

    layer_weights = []
    for in_features, out_features, activation in architecture:
        scale = (2.0 / in_features) ** 0.5  # He initialization

        # Weight matrix: out_features rows, in_features columns
        weights = [
            [(random.random() * 2 - 1) * scale for _ in range(in_features)]
            for _ in range(out_features)
        ]

        # Bias vector
        bias = [0.0 for _ in range(out_features)]

        layer_weights.append((weights, bias, activation))

    return layer_weights


def export_from_pytorch(model_path: str, output_path: str) -> None:
    """
    Export weights from a PyTorch checkpoint.

    Args:
        model_path: Path to PyTorch .pt or .ckpt file
        output_path: Output Prolog file path
    """
    if not TORCH_AVAILABLE:
        print("Error: PyTorch not available. Install with: pip install torch")
        sys.exit(1)

    # Load checkpoint
    checkpoint = torch.load(model_path, map_location='cpu')

    # Handle different checkpoint formats
    if 'state_dict' in checkpoint:
        state_dict = checkpoint['state_dict']
    else:
        state_dict = checkpoint

    # Extract layer weights
    # Expected keys: mlp.layers.0.weight, mlp.layers.0.bias, etc.
    layer_weights = []
    layer_id = 0

    # Default activations for SRO Decoder architecture
    activations = ['swish', 'swish', 'swish', 'swish', 'linear']

    while True:
        # Try different key patterns
        weight_keys = [
            f'mlp.layers.{layer_id * 2}.weight',  # With activation layers
            f'layers.{layer_id * 2}.weight',
            f'layer_{layer_id}.weight',
            f'weights.{layer_id}',
        ]

        weight = None
        for key in weight_keys:
            if key in state_dict:
                weight = state_dict[key]
                break

        if weight is None:
            break

        # Find corresponding bias
        bias_keys = [
            f'mlp.layers.{layer_id * 2}.bias',
            f'layers.{layer_id * 2}.bias',
            f'layer_{layer_id}.bias',
            f'biases.{layer_id}',
        ]

        bias = None
        for key in bias_keys:
            if key in state_dict:
                bias = state_dict[key]
                break

        if bias is None:
            bias = torch.zeros(weight.shape[0])

        # Convert to lists
        # Note: PyTorch Linear stores weights as [out_features, in_features]
        # but our mat_vec expects [out_features, in_features] (rows are output neurons)
        weights_list = weight.tolist()
        bias_list = bias.tolist()

        activation = activations[layer_id] if layer_id < len(activations) else 'linear'
        layer_weights.append((weights_list, bias_list, activation))

        layer_id += 1

    if not layer_weights:
        print(f"Error: Could not find weights in {model_path}")
        print(f"Available keys: {list(state_dict.keys())}")
        sys.exit(1)

    export_mlp_weights(layer_weights, output_path)


def main():
    parser = argparse.ArgumentParser(
        description='Export neural network weights to SWI-Prolog format'
    )
    parser.add_argument(
        '--model', '-m',
        help='Path to PyTorch model checkpoint (.pt or .ckpt)'
    )
    parser.add_argument(
        '--output', '-o',
        default='weights.pl',
        help='Output Prolog file path (default: weights.pl)'
    )
    parser.add_argument(
        '--random', '-r',
        action='store_true',
        help='Generate random weights instead of loading from file'
    )
    parser.add_argument(
        '--precision', '-p',
        type=int,
        default=8,
        help='Decimal precision for weights (default: 8)'
    )

    args = parser.parse_args()

    if args.random:
        # SRO Decoder Ring architecture: 1 -> 6 -> 12 -> 24 -> 6 -> 1
        architecture = [
            (1, 6, 'swish'),
            (6, 12, 'swish'),
            (12, 24, 'swish'),
            (24, 6, 'swish'),
            (6, 1, 'linear'),
        ]
        layer_weights = generate_random_weights(architecture)
        export_mlp_weights(layer_weights, args.output)
    elif args.model:
        export_from_pytorch(args.model, args.output)
    else:
        parser.print_help()
        print("\nError: Specify --model or --random")
        sys.exit(1)


if __name__ == '__main__':
    main()
